services:
  skychat_traefik:
    ports:
      - 8085:8080
    environment:
      - MODE=DEVELOPMENT
  skychat_frontend:
    ports:
      - 5173:5173
    build:
      context: .
      dockerfile: app/client/Dockerfile-dev
    volumes:
      - ./app:/workdir/app:ro
  skychat_backend:
    build:
      context: .
      dockerfile: app/server/Dockerfile-dev
    volumes:
      - ./app:/workdir/app:ro
