import SQL from 'sql-template-strings';
import { DatabaseHelper } from './DatabaseHelper.js';
import { StoredRoom } from './Room.js';

export type RoomDBRow = {
    id: number;
    name: string;
    order: number;
    plugin_group_names: string[];
    is_private: boolean;
    whitelist: string[];
    is_main: boolean;
    created_at: Date;
    updated_at: Date;
    deleted_at: Date | null;
};

export class RoomController {
    /**
     * Get all non-deleted rooms from the database
     */
    static async getAll(): Promise<{ id: number; data: StoredRoom; createdAt: Date }[]> {
        const result = await DatabaseHelper.db.query(
            SQL`SELECT id, name, "order", plugin_group_names, is_private, whitelist, is_main, created_at FROM rooms WHERE deleted_at IS NULL ORDER BY id`,
        );
        return result.rows.map((row: RoomDBRow) => ({
            id: row.id,
            data: {
                name: row.name,
                order: row.order,
                pluginGroupNames: row.plugin_group_names,
                isPrivate: row.is_private,
                whitelist: row.whitelist,
                main: row.is_main,
            },
            createdAt: row.created_at,
        }));
    }

    /**
     * Check if any non-deleted rooms exist
     */
    static async hasRooms(): Promise<boolean> {
        const result = await DatabaseHelper.db.query(SQL`SELECT 1 FROM rooms WHERE deleted_at IS NULL LIMIT 1`);
        return result.rows.length > 0;
    }

    /**
     * Insert a new room (ID auto-generated by the database). Returns the assigned ID.
     */
    static async insert(data: StoredRoom): Promise<number> {
        const result = await DatabaseHelper.db.query(SQL`
            INSERT INTO rooms (name, "order", plugin_group_names, is_private, whitelist, is_main)
            VALUES (
                ${data.name},
                ${data.order},
                ${JSON.stringify(data.pluginGroupNames)}::jsonb,
                ${data.isPrivate},
                ${JSON.stringify(data.whitelist)}::jsonb,
                ${!!data.main}
            )
            RETURNING id
        `);
        return result.rows[0].id;
    }

    /**
     * Update a room. Does NOT overwrite is_deleted.
     */
    static async update(id: number, data: StoredRoom): Promise<void> {
        await DatabaseHelper.db.query(SQL`
            UPDATE rooms SET
                name = ${data.name},
                "order" = ${data.order},
                plugin_group_names = ${JSON.stringify(data.pluginGroupNames)}::jsonb,
                is_private = ${data.isPrivate},
                whitelist = ${JSON.stringify(data.whitelist)}::jsonb,
                is_main = ${!!data.main},
                updated_at = NOW()
            WHERE id = ${id}
        `);
    }

    /**
     * Soft-delete a room
     */
    static async softDelete(id: number): Promise<void> {
        await DatabaseHelper.db.query(SQL`UPDATE rooms SET deleted_at = NOW() WHERE id = ${id}`);
    }

    /**
     * Get the message ID counter from the database. Returns null if not set.
     */
    static async getMessageIdCounter(): Promise<number | null> {
        const result = await DatabaseHelper.db.query(SQL`SELECT value FROM state_counters WHERE key = 'messageId'`);
        return result.rows.length > 0 ? result.rows[0].value : null;
    }

    /**
     * Save the message ID counter to the database
     */
    static async saveMessageIdCounter(messageId: number): Promise<void> {
        await DatabaseHelper.db.query(SQL`
            INSERT INTO state_counters (key, value) VALUES ('messageId', ${messageId})
            ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
        `);
    }

    /**
     * Insert a room during migration (within a transaction managed by the caller).
     * Uses ON CONFLICT DO NOTHING for idempotency.
     */
    // eslint-disable-next-line no-unused-vars
    static async insertForMigration(client: { query: (q: any) => Promise<any> }, id: number, data: StoredRoom): Promise<void> {
        await client.query(SQL`
            INSERT INTO rooms (id, name, "order", plugin_group_names, is_private, whitelist, is_main)
            VALUES (
                ${id},
                ${data.name},
                ${data.order},
                ${JSON.stringify(data.pluginGroupNames)}::jsonb,
                ${data.isPrivate},
                ${JSON.stringify(data.whitelist)}::jsonb,
                ${!!data.main}
            )
            ON CONFLICT (id) DO NOTHING
        `);
    }

    /**
     * Insert message ID counter during migration (within a transaction managed by the caller).
     */
    // eslint-disable-next-line no-unused-vars
    static async saveMessageIdCounterForMigration(client: { query: (q: any) => Promise<any> }, messageId: number): Promise<void> {
        await client.query(SQL`
            INSERT INTO state_counters (key, value) VALUES ('messageId', ${messageId})
            ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
        `);
    }
}
