
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faUsers,
    faBell,
    faKey,
    faCircleDot,
    faPaperPlane,
    faGlobe,
    faLock,
    faEllipsis,
    faClock,
    faLinkSlash,
    faUpRightAndDownLeftFromCenter,
    faDownLeftAndUpRightToCenter,
    faTv,
    faSlash,
    faExpand,
    faCompress,
    faPowerOff,
    faChevronDown,
    faChevronUp,
    faCaretLeft,
    faCaretRight,
    faPause,
    faPlus,
    faMinus,
    faBan,
    faList,
    faToggleOn,
    faToggleOff,
    faForwardStep,
    faUpload,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faUsers,
    faBell,
    faKey,
    faCircleDot,
    faPaperPlane,
    faGlobe,
    faLock,
    faEllipsis,
    faClock,
    faLinkSlash,
    faUpRightAndDownLeftFromCenter,
    faDownLeftAndUpRightToCenter,
    faTv,
    faSlash,
    faExpand,
    faCompress,
    faPowerOff,
    faChevronDown,
    faChevronUp,
    faCaretLeft,
    faCaretRight,
    faPause,
    faPlus,
    faMinus,
    faBan,
    faList,
    faToggleOn,
    faToggleOff,
    faForwardStep,
    faUpload,
);

export default library;
