name: Docker build CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run setup
            - run: echo $USER; id -u $USER; id -g $USER
            - run: cp .github/workflows/.env.github .env
            - run: docker compose up -d
